
# File: .github/workflows/azure_webapp.yml

on: 
  workflow_dispatch:

name: app

jobs:
  build-and-deploy:
    runs-on: **
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
      
    - name: Setup Node 10.x
      uses: actions/setup-node@v1
      with:
        **

    - name: 'npm install, build, and test'
      run: |
        **

    - name: Azure Login
      uses: azure/login@v1
      with:
        **

    - name: 'Azure webapp deploy'
      uses: azure/webapps-deploy@v2
      with:
        app-name: **
        package:  ${{ github.workspace }}/app
